name: Go

on:
  push:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: go test ./core ./miner/... ./internal/ethapi/... ./les/...

    - name: Build
      run: make geth

  e2e:
    name: End to End
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      id: go

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: make geth
